### PR TITLE
[DEV-4651] start refactoring bar charts for tooltips

### PR DESCRIPTION
**Pull request by adamdoe**

### CODE REVIEW

**Comment by adamdoe** [comment]
@Atash3000 can you check this PR out for review. Try to review all of the different chart types you can think of to see if any are breaking. Thanks!

**Review by Atash3000 — COMMENTED** [review]
Everything looks fine for me.I did made some changes and tested on Editor. Only thing is tooltips on horizontal bars including lollipops/horizontal not working, probably it is easy for you to see it.

**Comment by Atash3000** [comment]
i did more changes, also on vertical and horizontal non stacked  files we have tooltips. if these are not being used we can remove them, carefefully. also confidence keys are not working.. i could not fast fix there yet. if you have knowledge on these please check. we need cleanup horizontal non stacked file more. i did only safe clean and also tested on editor.

**Comment by Atash3000** [comment]
if we are not using this   const tooltip = `<ul>
                  ${config.legend.showLegendValuesTooltip && config.runtime.seriesLabels && hasMultipleSeries ? `${config.runtime.seriesLabels[bar.key] || ''}<br/>` : ''}
                  <li class="tooltip-heading">${yAxisTooltip}</li>
                  <li class="tooltip-body">${xAxisTooltip}</li>
                    </li></ul>` and        data-tooltip-html={tooltip} tooltips anymore let me know , i will remove these.

**Pull request merged**
