### PR TITLE
23719 provide option to freeze header in data table

### PR DESCRIPTION
**Pull request by ernestweems**
Charts:please note the existing behavior is that on all screens the scroll behavor already exist. On larger screens in order see the scroll behavior table rows have take up all the visual screen to cause the scroll.
Upon this discovery one might want to consider if  Freeze Data Table Header is still needed in Charts component or Editor component.
extra rows exsiting scroll behavior high row count 13-10_36_39

### CODE REVIEW

**Comment by ernestweems** [comment]
@adamdoe please see commit comments

**Comment by adamdoe** [comment]
@ernestweems can you apply your changes from a branch off of the dev branch and target the dev branch instead of main here?

**Comment by ernestweems** [comment]
@adamdoe I will update

**Comment by joshlacey** [comment]
Can this stickyHeader prop be used? https://github.com/CDCgov/cdc-open-viz/blob/5d9c8f567f9468b4198949ece4a1b588072cb9cf/packages/core/components/Table/Table.tsx#L27

**Comment by ernestweems** [comment]
> Can this stickyHeader prop be used?
> 
> https://github.com/CDCgov/cdc-open-viz/blob/5d9c8f567f9468b4198949ece4a1b588072cb9cf/packages/core/components/Table/Table.tsx#L27



> Can this stickyHeader prop be used?
> 
> https://github.com/CDCgov/cdc-open-viz/blob/5d9c8f567f9468b4198949ece4a1b588072cb9cf/packages/core/components/Table/Table.tsx#L27

are you asking about reuse ?

**Comment by adamdoe** [comment]
@ernestweems - it sounds like we're looking for passing freezeTableHeader in on the `<DataTable freezeTableHeader={true} />` component.  In addition to changing the base, can you update that prop?

**Comment by ernestweems** [comment]
> > > Can this stickyHeader prop be used?
> > > https://github.com/CDCgov/cdc-open-viz/blob/5d9c8f567f9468b4198949ece4a1b588072cb9cf/packages/core/components/Table/Table.tsx#L27
> > 
> > 
> > > Can this stickyHeader prop be used?
> > > https://github.com/CDCgov/cdc-open-viz/blob/5d9c8f567f9468b4198949ece4a1b588072cb9cf/packages/core/components/Table/Table.tsx#L27
> > 
> > 
> > are you asking about reuse ?
> 
> Yes, the link shows an area of the code base that to me seems to concern the feature you are trying to build, but I'm not seeing this section referenced anywhere in your PR.
Apologies for the delayed response this prop existed before I implemented my feature I it was not reusable for what I was implementing.

**Comment by ernestweems** [comment]
> @ernestweems - it sounds like we're looking for passing freezeTableHeader in on the `<DataTable freezeTableHeader={true} />` component. In addition to changing the base, can you update that prop?

@adamdoe

**Comment by ernestweems** [comment]
@joshlacey I will be making a new branch and PR.

**Pull request closed without merging**
