### PR TITLE
DRAFT: Fix/brush

### PR DESCRIPTION
**Pull request by Atash3000**
## Briefly describe your changes
I created withBrush.jsx which uses HOC from React. we should not be creating any components in LinearChart. i showed example how to do it. We need to tell Tim to cleanup Linear chart from any brush logic including SVG height and width logic.we have better ways of doing it.and also we  do all calculationins inside of withBrush.jsx and also we need to remove BrushHandle.jsx file with is redundant.Please tell Tim to follow this.Thank you.
## Checklist before requesting a review
- [ ] My pull request was branched from and targets the test branch
- [ ] I have performed a self-review of my code
- [ ] I have manually tested all packages affected (bonus points for automations)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have checked to ensure there aren't other open pull requests for the same change

## Did you test your feature in the following environments?
- [ ] Standalone Component
- [ ] Standalone Full Editor
- [ ] CDC Internal Checks

### CODE REVIEW

**Comment by Atash3000** [comment]
@adamdoe please tell Tim to review this PR and to follow rule of this PR. Our Linear chart gets now more code and complex.We dont need to create a components inside Linear chart.jsx. Also look at this PR and see maybe you could add some additional logic to make code more clear.Thank you.

**Comment by tturnerswdev33** [comment]
@Atash3000 Thanks for the suggestions.  The brush code was just a temporary test version so that several people could look at it and comment before we add similar to other chart types.  I agree that using HOC code version is better.  I will discuss with ADam and we will make adjustments.

**Comment by tturnerswdev33** [comment]
Also @Atash3000 did you compile and test this?  As I pulled this branch and it does not render the brush...
OR were you just trying to suggest how to use the HOC format but did not really test this...

**Comment by tturnerswdev33** [comment]
I created a separate branch off this one and finished the edits so closing this one.

**Pull request closed without merging**
