### PR TITLE
Dev 6649

### PR DESCRIPTION
**Pull request by mpallansch**

### CODE REVIEW

**Comment by adamdoe** [comment]
@mpallansch tested with vertical and horizontal bar charts. The only thing I'm seeing is that the date/category height isn't working. The spacing looks nice, I'm just wondering if we need to account for that still or hide it.

**Review by adamdoe — CHANGES_REQUESTED** [review]
@mpallansch tested with vertical and horizontal bar charts. The only thing I'm seeing is that the date/category height isn't working. The spacing looks nice, I'm just wondering if we need to account for that still or hide it.

**Comment by mpallansch** [comment]
> @mpallansch tested with vertical and horizontal bar charts. The only thing I'm seeing is that the date/category height isn't working. The spacing looks nice, I'm just wondering if we need to account for that still or hide it.

Can you elaborate on the issue you're seeing?

**Comment by adamdoe** [comment]
When I open the Date/Category axis and adjust the height nothing is happening.

**Comment by adamdoe** [comment]
Screen Shot 2024-05-16 at 1 32 05 PM

@mpallansch  - This setting doesn't seem to change anything.

**Comment by mpallansch** [comment]
> When I open the Date/Category axis and adjust the height nothing is happening.

I added another commit, let me know if that fixes the issue

**Pull request merged**
